// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH5cmz0LEsIXqPaROYyoZm1d17EUmyR_I',
    appId: '1:51812634523:web:ed658fd6268703aee91b3e',
    messagingSenderId: '51812634523',
    projectId: 'pasnallized-alarm-service',
    authDomain: 'pasnallized-alarm-service.firebaseapp.com',
    storageBucket: 'pasnallized-alarm-service.firebasestorage.app',
    measurementId: 'G-QEMY3YQM1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyNO5H2uugbXK-Ep9f8fURu7JGGLHgvRY',
    appId: '1:51812634523:android:84a5b48431efbb87e91b3e',
    messagingSenderId: '51812634523',
    projectId: 'pasnallized-alarm-service',
    storageBucket: 'pasnallized-alarm-service.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2tRondXwToqsGs-z4fk5AQIntvo7ZZpE',
    appId: '1:51812634523:ios:9948ca5c810c9472e91b3e',
    messagingSenderId: '51812634523',
    projectId: 'pasnallized-alarm-service',
    storageBucket: 'pasnallized-alarm-service.firebasestorage.app',
    iosBundleId: 'com.example.stopSnoring',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBH5cmz0LEsIXqPaROYyoZm1d17EUmyR_I',
    appId: '1:51812634523:web:4cd5531e76faa5ede91b3e',
    messagingSenderId: '51812634523',
    projectId: 'pasnallized-alarm-service',
    authDomain: 'pasnallized-alarm-service.firebaseapp.com',
    storageBucket: 'pasnallized-alarm-service.firebasestorage.app',
    measurementId: 'G-GR745JSYX8',
  );
}
